version: "3.7"

services:
    web:
        image: practise_web:0.1
        build: ./web
        ports:
            - "8000:8000"
        volumes:
            - ./web:/usr/src/app
        command: python manage.py runserver 0:8000


